[tool.poetry]
name = "demo-sanchay"
version = "0.1.0"
description = "No Description for"
authors = ["Sanchay Jain"]

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
fastapi = "^0.103.2"
uvicorn = "^0.23.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"